ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}-slim

LABEL maintainer "Mathieu Lemay <acidrain1@gmail.com>"

ARG POETRY_VERSION
ENV POETRY_VERSION ${POETRY_VERSION}

RUN set -eu; \
    apt-get update; \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get install -y --no-install-recommends curl git gcc libffi-dev libc6-dev; \
    \
    curl -sSL https://install.python-poetry.org \
        | python - --version "${POETRY_VERSION}"; \
    \
    rm -rf ~/.cache; \
    apt-mark auto '.*' > /dev/null; \
    [ -z "${savedAptMark}" ] || apt-mark manual ${savedAptMark}; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*;

ENV PATH="/root/.local/bin:$PATH"
