FROM python:__PYTHON_VERSION__

LABEL maintainer "Mathieu Lemay <acidrain1@gmail.com>"

ENV POETRY_VERSION __POETRY_VERSION__

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py \
    | python - --version "${POETRY_VERSION}"

ENV PATH="/root/.poetry/bin:$PATH"
