FROM python:3.9

LABEL maintainer "Mathieu Lemay <acidrain1@gmail.com>"

RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

ENV PATH="/root/.poetry/bin:$PATH"
